<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CustomerOrder;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGroupedByOrder(CustomerOrder $order)
    {
        return $this->createQueryBuilder('orderItem')
                    ->select('count(orderItem) as item_count, orderItem as item')
                    ->where('orderItem.order = :order')
                    ->groupBy('orderItem.price, orderItem.product')
                    ->orderBy('orderItem.product')
                    ->setParameter('order', $order)
                    ->getQuery()
                    ->getResult()
            ;
    }
}
