<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

	public function findAllProducts()
	{
		return $this
			->createQueryBuilder('product')
			->getQuery()
			->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY)
		;
	}

	public function findActiveProduct($id)
	{
		return $this
		->createQueryBuilder('product')
		->where('product.id = :id')
		->andWhere('product.active = true')
		->setParameter('id', $id)
		->getQuery()
		->getOneOrNullResult();

	}

	public function findActiveByCategory(Category $category)
	{
		return $this
		->createQueryBuilder('product')
		->join('product.category', 'category')
		->where('category.active = true')
		->andWhere('product.active = true')
		->getQuery()
		->getOneOrNullResult();

	}
}
