# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    customer1:
                        password: customer1
                        roles: 'ROLE_CUSTOMER'

                    customer2:
                        password: customer2
                        roles: 'ROLE_CUSTOMER'

                    customer3:
                        password: customer3
                        roles: 'ROLE_CUSTOMER'

                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path : ^/admin, roles: ROLE_ADMIN }
        - { path : ^/customers, roles: ROLE_CUSTOMER }
